version: '3.8'
services:
  db:
    container_name: mysql
    build:
      dockerfile: mysql.Dockerfile
    restart: always
    ports:
      - '3306:3306'
  db_interface:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    links:
      - 'db:database'
